### ISSUE TITLE
Automated REST API documentation

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#10]
I like automated docs for the REST API. It's convenient and enforces a consistent inline class / method documentation style. Perhaps Swagger can help. I found [play-doc](https://github.com/playframework/play-doc). Also there is `activator doc` but that seems to be more for internal documentation.

**Comment by mgcuthbert** [comment]
Forgot this was a issue, but in recent PR https://github.com/maproulette/maproulette2/pull/83 I integrated Swagger into MapRoulette. I have not updated all the endpoints correctly, so using default and the following 2 issues still exist:
1) Because we are using generics in our code, the response class is not set correctly, need to figure out how to do that.
2) There is a bug in Swagger-play with Play Framework 2.5.x which we are using, so I had to use a repo that has the fix in it. As soon as the fix goes to the master branch, I need to switch the dependency out back to the correct repo.
