### ISSUE TITLE
The identifier field is not returned for the Challenge object

### ISSUE THREAD

**Issue by beataj-telenav** [maproulette/maproulette2#110]
The identifier field is not returned for the Challenge object in the case of the following methods:
- list project children method
- get challenge method
- list challenges method

**Comment by mgcuthbert** [comment]
So this is where the swagger tools come in very handy. And hopefully we can start getting something out sooner rather than later. The "identifier" field was removed a while ago, but the API documents (which were written right in the beginning) have not been updated since then. Since that change, the name field has become the primary unique identifier (along with the non-editable ID field) for any of the objects in the system.

My apologies for the API being out of date. Hopefully we will have the swagger UI up and running with the latest up to date API information fairly soon.

**Comment by beataj-telenav** [comment]
Thanks for the clarification. I will remove the "identifier" field from the logic of the MapRouletteLoader component.
