### ISSUE TITLE
Overpass challenge creation only works with nodes

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#125]
When a query contains ways, we load both the nodes **and** the ways as tasks. Any 'way' (pun intended) to make it work with ways as well?

Workaround for now is to export Geojson from Overpass and load it that way.

**Comment by mgcuthbert** [comment]
It works with ways, however you need to make sure that you include "out body geom qt;" which will force the geometry to be inside the ways instead of the ways just referencing the nodes. By doing this I don't have to try and get the Node information separately, which is doable but will slow the process and take a bit of time to complete.

**Comment by mvexel** [comment]
Gotcha, I need to try this out and work on a tutorial doc for this aspect.
