### ISSUE TITLE
Marker is too narrow to show enough information

### ISSUE THREAD

**Issue by alarobric** [maproulette/maproulette2#235]
The marker for the task shows the tags from the GeoJSON, but it is too narrow to see the full text, and no scroll bars are available.

![image](https://cloud.githubusercontent.com/assets/321603/21066260/877ddede-be19-11e6-8ec3-0de11c146a4b.png)

**Comment by mgcuthbert** [comment]
This is caused by the PR #222 in mapping.js lines 727 to 734

+                        var printLine = k+": "+v;
 +                        if(printLine.length > 22){
 +                                popupString += printLine.slice(0,20)+".."+ '<br />';
 +                                
 +                            }
 +                        else{
 +                            popupString += printLine+ '<br />';
 +                        }

**Comment by dalekunce** [comment]
+1 for fixing this.
