### ISSUE TITLE
dead link in Wiki

### ISSUE THREAD

**Issue by matkoniecz** [maproulette/maproulette2#513]
https://github.com/maproulette/maproulette2/wiki/Creating-MapRoulette-Challenges-from-GeoJSON has link in

> covered the Wizard in general in a previous post

leading to https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges that is not existing

**Comment by matkoniecz** [comment]
Content was saved by IA - see https://web.archive.org/web/20170218003920/https://github.com/maproulette/maproulette2/wiki/Introducing-New-MapRoulette---Part-1.-Creating-and-Maintaining-Challenges

**Comment by mgcuthbert** [comment]
That information is very out of date and we have gone through a couple of iterations of MapRoulette since that document was written. So I have updated the document to note that it is deprecated and pointed to the new "Help and Resources" documentation that should contain more up to date information. You can find it here: 
https://github.com/osmlab/maproulette3/wiki/Help-and-Resources
