### ISSUE TITLE
auto select OSM objects in JOSM based on task geometry's `osmid` property

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#77]
In MapRoulette 1, any task geometry that had a property `osmid` would be pre-selected in JOSM. We should carry this behavior over to New MapRoulette

**Comment by mvexel** [comment]
related to #161

**Comment by beataj-telenav** [comment]
Any news related this feature?

**Comment by ianmcorvidae** [comment]
Looking at the code and setting some breakpoints for my own challenge (which is an overpass query looking for nodes only, if it matters): mapping.js looks for `feature.properties.osmid` but `feature.properties` doesn't include an 'osmid' property (just the actual OSM tags on the feature (though, strangely, quoted with two sets of double-quotes). Perhaps overpass needs to be instructed to provide it somehow?

Other than that, #195 will make it work, since the `select` URL property is after the `changeset_comment` one that was being broken by the bug that PR fixes.

**Comment by mvexel** [comment]
I think this is important to have, assigning P1

**Comment by mvexel** [comment]
This is captured in #161
